# Generated by Django 5.1.6 on 2025-03-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='added as default', max_length=80),
            preserve_default=False,
        ),
    ]
