# Generated by Django 5.1.6 on 2025-03-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_stripe_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_pid',
            new_name='stripe_id',
        ),
    ]
