# Generated by Django 5.1.6 on 2025-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_stripe_pid_order_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
