# Generated by Django 5.1.6 on 2025-02-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chain_length',
            field=models.CharField(choices=[('16', '16 Inches'), ('18', '18 Inches'), ('20', '20 Inches'), ('22', '22 Inches'), ('24', '24 Inches'), ('26', '26 Inches'), ('28', '28 Inches')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='chain_thickness',
            field=models.CharField(choices=[('1', '1mm'), ('2', '2mm'), ('3', '3mm'), ('4', '4mm'), ('5', '5mm')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_type',
            field=models.CharField(choices=[('GL', 'Gold'), ('RG', 'Rose Gold'), ('YG', 'Yellow Gold'), ('WG', 'White Gold'), ('SS', 'Sterling Silver'), ('BRZ', 'Bronze'), ('TIT', 'Titanium')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stone_type',
            field=models.CharField(choices=[('DI', 'Diamond'), ('PR', 'Pearl'), ('QZ', 'Quartz'), ('TP', 'Topaz'), ('SYN', 'Synthetic')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('RG', 'Ring'), ('CF', 'Cuff'), ('NL', 'Necklace')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='default sku', max_length=254),
            preserve_default=False,
        ),
    ]
